### PR TITLE
Address macos CRAN checks

### LINKED ISSUE #10: Address CRAN package check macOS issues
Before submitting a new version of rTRNG to CRAN, we should address the macOS errors on the CRAN [package check page](https://cran.r-project.org/web/checks/check_results_rTRNG.html).

In particular, the following issues are reported

### Some tests are failing on macOS
```
══ testthat results ═══════════════════════════════════════════════════════════
[ OK: 581 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 30 ]
1. Failure: $split errors for out-of-range subsequence indices (@test-TRNG.Engine.R#264)
...
```
In fact we have exactly 30 warnings when running tests in Ubuntu for the same test reported here
```
test-TRNG.Engine.R:264: warning: $split errors for out-of-range subsequence indices
`e$split(p, 0L)` generated an S3 error and you are testing the error message.
* The error has class = c("std::invalid_argument", "C++Error", "error", "condition")
* Testing with `class` is more robust than testing with `regexp`.
* Do you want `expect_error(..., class = "std::invalid_argument")`?
```
Most likely this is detected as a failure under macOS, and fixing the expectation as hinted in the warning message might solve the issue.

### Re-building the vignettes fails on macOS (and Solaris) 

This happens for C++ code chunks using `sourceCpp()`
```
Library not loaded: rTRNG.so
```

### PR DESCRIPTION
**Pull request by riccardoporreca**
Closes #10

See in particular https://github.com/miraisolutions/rTRNG/issues/10#issuecomment-594092097

### CODE REVIEW

File: R/rTRNG-package.R [hunk 1]
```diff
@@ -45,6 +45,12 @@
 #'       \code{importFrom(rTRNG, TRNG.Version)} in the NAMESPACE file, and
 #'       setting relevant linker flags (via \code{\link[rTRNG]{LdFlags}}) and
 #'       C++11 compilation (\code{CXX_STD = CXX11}) in Makevars[.win].
+#'     \item
+#'       Note that C++ code using the TRNG library (sourced via
+#'       \code{Rcpp::sourceCpp} or part of an \R package) might fail on certain
+#'       systems due issues with building and linking against \pkg{rTRNG}. This
```
Comment (RolandASc) [inline R/rTRNG-package.R]:
```suggestion
#'       systems due to issues with building and linking against \pkg{rTRNG}. This
```

File: R/rTRNG-package.R [hunk 2]
```diff
@@ -45,6 +45,12 @@
...
+#'       is typically the case for  macOS, and can be in general checked using
```
Comment (RolandASc) [inline R/rTRNG-package.R]:
```suggestion
#'       is typically the case for macOS, and can generally be checked using
```

File: README.Rmd [hunk 3]
```diff
@@ -199,3 +198,13 @@ Creating an R package with C++ code using the TRNG library and headers through
     - Makevars: `PKG_LIBS += $(shell ${R_HOME}/bin/Rscript -e "rTRNG::LdFlags()")`
     - Makevars.win: `PKG_LIBS += $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" -e "rTRNG::LdFlags()")`
 
+### Note about C++ code on macOS
+
+C++ code using the TRNG library (sourced via `Rcpp::sourceCpp` or part of an R
+package) might fail on certain systems due issues with building and linking
```
Comment (RolandASc) [inline README.Rmd]:
```suggestion
package) might fail on certain systems due to issues with building and linking
```

File: README.Rmd [hunk 4]
```diff
@@ -199,3 +198,13 @@ Creating an R package with C++ code using the TRNG library and headers through
...
+against **rTRNG**. This is typically the case for  **macOS**, and can be in
+general checked by running
```
Comment (RolandASc) [inline README.Rmd]:
```suggestion
against **rTRNG**. This is typically the case for  **macOS**, and can generally be checked by running
```

File: vignettes/mcMat.Rmd [hunk 5]
```diff
@@ -13,16 +13,19 @@ vignette: >
 ```{r setup, include=FALSE}
 knitr::opts_chunk$set(collapse = TRUE)
 options(digits = 5) # for kable
+linking_ok <- rTRNG::check_rTRNG_linking()
 ```
 
 
 ```{r include=FALSE, cache=FALSE}
```
Comment (RolandASc) [inline vignettes/mcMat.Rmd]:
```suggestion
```{r code, include=FALSE, cache=FALSE}
```

File: vignettes/rTRNG.Rmd [hunk 6]
```diff
@@ -148,3 +149,15 @@ Creating an R package with C++ code using the TRNG library and headers through
 - setting the relevant linker flags in Makevars[.win] via `rTRNG::LdFlags()`
     - Makevars: `PKG_LIBS += $(shell ${R_HOME}/bin/Rscript -e "rTRNG::LdFlags()")`
     - Makevars.win: `PKG_LIBS += $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" -e "rTRNG::LdFlags()")`
+
+
+### Note about C++ code on macOS
+
+C++ code using the TRNG library (sourced via `Rcpp::sourceCpp` or part of an R
+package) might fail on certain systems due issues with building and linking
```
Comment (RolandASc) [inline vignettes/rTRNG.Rmd]:
```suggestion
package) might fail on certain systems due to issues with building and linking
```

File: vignettes/rTRNG.Rmd [hunk 7]
```diff
@@ -148,3 +149,15 @@ Creating an R package with C++ code using the TRNG library and headers through
...
+against **rTRNG**. This is typically the case for  **macOS**, and can be in
+general checked by running
```
Comment (RolandASc) [inline vignettes/rTRNG.Rmd]:
```suggestion
against **rTRNG**. This is typically the case for **macOS**, and can generally be checked by running
```

**Comment by RolandASc** [comment]
Looks good to me in general :+1:
